# Generated by Django 3.2.9 on 2021-12-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_options'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='train',
            unique_together={('travel_time', 'from_city', 'to_city')},
        ),
    ]
