"""
Django settings for travel project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

DB_NAME = os.environ.get('DB_NAME')
DB_PASSWORD = os.environ.get('DB_PASSWORD')
DB_HOST = os.environ.get('DB_HOST')
DB_USER = os.environ.get('DB_USER')
SECRET_KEY = os.environ.get('SECRET_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*', ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cities.apps.CitiesConfig',
    'trains.apps.TrainsConfig',
    'routes.apps.RoutesConfig',
    'accounts.apps.AccountsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'travel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'travel.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': 5432,  # по умолчанию порт для postgresql
    }
}

import dj_database_url

db = dj_database_url.config()
DATABASES['default'].update(db)

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'  # 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# -------------------------------------------------------- STATIC settings

STATIC_URL = '/static/'

# здесь мы указываем откуда будем доставать статику и подключать к шаблону,
# с помощью тега {% static 'css/style.css' %}
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# здесь мы указываем куда django будет собирать всю статику проекта при команде collectstatic
# на самом деле это основная папка, от куда берется статика проекта
# и должна называться они staticfiles
STATIC_ROOT = BASE_DIR.joinpath('staticfiles')
# -------------------------------------------------------- STATIC settings


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------- LOGGING settings
# https://docs.djangoproject.com/en/3.2/topics/logging/
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {  # formatters - отвечает за то, каким образом будет выводиться сообщение
        'verbose': {
            'format':
                '{levelname} {asctime} {module} {message}',
            #   {levelname} - уровень данного сообщения
            #   {asctime} - время
            #   {module} - модуль из которого происходил запрос
            #   {message} - сам запрос, который необходимо фиксировать
            'style':
                '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        # 'special': {
        #     '()': 'project.logging.SpecialFilter',
        #     'foo': 'bar',
        # },
        'require_debug_true': {  # require_debug_true - мы будем фиксировать логирование, когда DEBUG = True
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {  # хэндлеры говорят о том, каким образом мы можем обрабатывать полученное сообщение
        # куда их выводить, в консоль, в файл, на почту?
        'console': {  # вывести в консоль
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {  # вывести в файл
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR.joinpath('log/application.log'),
            'formatter': 'verbose',
        },
        # 'mail_admins': {  # послать по почте
        #     'level': 'ERROR',
        #     'class': 'django.utils.log.AdminEmailHandler',
        #     'filters': ['special']
        # }
    },
    'loggers': {  # что мы фактически фиксируем, и куда
        'django.db.backends': {  # 'django.db.backends' - настройки фиксации логирования запросов в бд
            'handlers': ['file'],  # в записываем в файл
            'level': 'DEBUG',
        },
        'django.request': {  # 'django.request' - настройки фиксации логирования HTTP запросов
            'handlers': ['file'],  # в записываем в файл
            'level': 'DEBUG',
            'propagate': False,
        },
        # 'django': {
        #     'handlers': ['console'],
        #     'propagate': True,
        # },
        # 'myproject.custom': {
        #     'handlers': ['console', 'mail_admins'],
        #     'level': 'INFO',
        #     'filters': ['special']
        # }
    }
}

# ! Важный момент:
# Здеесь мы будем фиксировать логирования, когда DEBUG = True
# 'require_debug_true': {
#             '()': 'django.utils.log.RequireDebugTrue',}

# А здесь сообщаем куда будем записывать логи (файл log):
# 'filename': BASE_DIR.joinpath('log/application.log'),

# Если DEBUG = False и мы уже на боевом сервере, перешли в продакшн,
# файл log (кужа мы бцдем записывать логи) всё равно должен быть

# Steps:
# 1. Добавляешь этот набор настроек в файл settings.py
# 2. Корректируешь там, то что нужно (в этом варианте всё необходимое уже есть)
# 3. Создаешь на уровне приложения папку log, и помещаешь туда пустой файл empty.txt (можно не совсем пустой)
# 4. Наслаждаешься логгированием, если DEBUG = True

# -------------------------------------------------------- LOGGING settings

